version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      android-deps:
        patterns:
          - "*"
  
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    groups:
      documentation-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
